#!/bin/bash
gst-launch-1.0 filesrc location="${1:-/tmp/radio-output}" ! queue ! \
    rawaudioparse sample-rate=24000 ! queue ! \
    audioconvert ! queue ! \
    audiocheblimit cutoff=6000 ! queue ! \
    vorbisenc ! queue ! \
    oggmux ! queue ! \
    tcpserversink host=127.0.0.1 port=4953

