#!/bin/sh
gst-launch-1.0 filesrc location=/tmp/radio-fifo ! queue ! \
    rawaudioparse sample-rate=24000 ! queue ! \
    audioconvert ! queue ! \
    audiocheblimit cutoff=6000 ! queue ! \
    autoaudiosink
