#!/bin/sh
gst-launch-1.0 filesrc location="${1:-/tmp/radio-output}" ! queue ! \
    rawaudioparse sample-rate=24000 ! queue ! \
    audioconvert ! queue ! \
    audiocheblimit cutoff=6000 ! queue ! \
    autoaudiosink
