#!/bin/sh
VIDEO=`ls /dev/video* | head -1`
PORT="8085"
#Loop on starting up the pipeline
while `echo -n`
do
    gst-launch-1.0 v4l2src device="${VIDEO}" ! omxh264enc ! tcpserversink max-lateness="18000000" port="${PORT}"
    sleep 1
done
