#!/bin/sh
VIDEO=`ls /dev/video* | head -1`
PORT="8085"
FILE="/home/osmc/Movies/recording.mp4"
FILE_BK="/home/osmc/Movies/recording-previous.mp4"
#Backup files
if [ -f ${FILE} ]
then
    rm -f ${FILE_BK}
    mv ${FILE} ${FILE_BK}
fi
#Loop on starting up the pipeline
while `echo -n`
do
    gst-launch-1.0 v4l2src device="${VIDEO}" ! omxh264enc ! tee name=t ! \
        queue ! tcpserversink max-lateness="18000000" port="${PORT}" t. ! \
        queue ! filesink location="${FILE}"
    sleep 1
done
