#!/bin/sh
####
# rtl-gst:
#
# A simple script for running the RTL-FM data reader, converting it to OGG/Vorbis format, and hosting it as part of
# a TCP server. This uses rtl_fm as the source of the data, and GStreamer to encode the data.
#
# @author lestarch
####
SAMPLE_RATE="48000"
PID_FILE="/var/run/sediq.pid"
# Check input arguments
if [ $# -lt 1 ]
then
    echo "[ERROR] Must supply a radio frequency to tune to."
    exit 3
fi
# Remove old PID and destroy any running processes
if [ -f "${PID_FILE}" ]
then
  kill `cat "${PID_FILE}"`
  kill -KILL `cat "${PID_FILE}"`
  rm "${PID_FILE}"
fi
# Command line for rtl_fm
RTL_FM="rtl_fm -M wbfm -s 200000 -r ${SAMPLE_RATE} -f ${1} -"
GST_PIPE="gst-launch-1.0 fdsrc  ! rawaudioparse sample-rate=`expr ${SAMPLE_RATE} / 2`  ! audioconvert ! vorbisenc ! oggmux ! tcpserversink"
# Run the pipeline
${RTL_FM} | ${GST_PIPE} &
echo "$?" > "${PID_FILE}"
exit 0
